### ISSUE TITLE
Liens permanents

### ISSUE THREAD

**Issue by corsac-s** [budget-ouvert/client#4]
Hello, merci pour l'outil de visualisation, c'est vraiment intéressant.

Je n'ai pas trouvé de moyen de faire des _permalinks_ pour partager des informations sur une action précise.

Ça pourrait être rajouté dans l'arborescence en haut à droite (et ça faciliterait la remontée dans l'arbre aussi).

**Comment by alexis-thual** [comment]
Tu as raison, c'est un incontournable !
Le plus efficace est peut-être d'enregistrer le state dans l'url. Il y a finalement peu d'informations à retenir pour décrire le state de la page : le `sourceType` (ex: `PLF`), la `year` et le `selectedNode` (ex: `PLF > Budget Général`). Je viens de tomber sur ça pour gérer la `location` avec React Router : https://stackoverflow.com/questions/35352638/how-to-get-parameter-value-from-query-string

**Comment by corsac-s** [comment]
Je n'y connais strictement rien en javascript donc je vais m'abstenir de commenter sur l'implémentation, désolé :)

**Comment by alexis-thual** [comment]
Done dans la PR #5 :)
